services:
  http:
    container_name: http
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./workspace:/workspace

  mongo:
    container_name: mongo
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: aiagent

volumes:
  mongo_data:
