services:
  aiagent:
    container_name: aiagent
    image: "drujensen/aiagent:latest"
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env-docker
    volumes:
      - ~/workspace:/home/ubuntu/workspace
      - ~/.ssh:/home/ubuntu/.ssh
      - ~/.gitconfig:/home/ubuntu/.gitconfig
    

  mongo:
    container_name: mongo
    image: "mongo:6.0"
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: aiagent
    

volumes:
  mongo_data:
