package entities

import "time"

// AIAgent represents an AI agent in the workflow automation platform.
// It defines the configuration, hierarchy, and behavior settings for an agent,
// stored in MongoDB as a document in the 'agents' collection.
//
// Key features:
// - Hierarchical structure: Supports parent-child relationships via ParentID and ChildrenIDs.
// - Tool integration: References tools by their IDs rather than embedding full Tool structs.
// - Flexible configuration: Uses a map to store provider-specific settings (e.g., model, temperature).
//
// Relationships:
// - Self-referential hierarchy via ParentID and ChildrenIDs (references AIAgent).
// - Many-to-many with Tool via Tools field (list of Tool IDs).
type AIAgent struct {
	ID                      string                 `bson:"_id,omitempty" json:"id"`                                    // Unique identifier, auto-generated by MongoDB if omitted
	Name                    string                 `bson:"name" json:"name"`                                           // Human-readable name of the agent, required
	Prompt                  string                 `bson:"prompt" json:"prompt"`                                       // Custom prompt defining the agent's behavior, required
	Tools                   []string               `bson:"tools" json:"tools"`                                         // List of Tool IDs assigned to the agent, required
	Configuration           map[string]interface{} `bson:"configuration" json:"configuration"`                         // Provider-specific settings (e.g., "provider": "openai", "temperature": 0.7), required
	ParentID                string                 `bson:"parent_id,omitempty" json:"parent_id"`                       // ID of the parent agent, optional for root agents
	ChildrenIDs             []string               `bson:"children_ids" json:"children_ids"`                           // List of child agent IDs, empty for leaf agents
	HumanInteractionEnabled bool                   `bson:"human_interaction_enabled" json:"human_interaction_enabled"` // Flag to enable/disable human oversight, defaults to true
	CreatedAt               time.Time              `bson:"created_at" json:"created_at"`                               // Timestamp of creation, set on insert
	UpdatedAt               time.Time              `bson:"updated_at" json:"updated_at"`                               // Timestamp of last update, updated on modification
}

// Notes:
// - Tools is a list of strings (Tool IDs) to avoid embedding large Tool objects, improving storage efficiency.
// - Configuration uses map[string]interface{} to support varying AI provider settings without schema changes.
// - MongoDB will generate an ObjectID for ID if not provided, which is converted to a string for consistency.
// - Edge cases: Empty Tools or ChildrenIDs lists are valid; validation occurs in the service layer.
// - Assumption: Timestamps are in UTC for consistency across the application.
// - JSON tags added to support REST API serialization; IDs stored as strings for consistency.
