package entities

import "time"

// AuditLog represents an entry in the audit trail for agent actions in the workflow automation platform.
// It is stored in MongoDB as a document in the 'audit_logs' collection and tracks what agents do,
// such as starting tasks or using tools, for monitoring and debugging purposes.
//
// Key features:
// - Action tracking: Records specific actions (e.g., "task_started", "tool_used") with details.
// - Agent association: Links logs to the responsible AIAgent.
//
// Relationships:
// - Many-to-one with AIAgent via AgentID.
type AuditLog struct {
	ID        string    `bson:"_id,omitempty"` // Unique identifier, auto-generated by MongoDB if omitted
	AgentID   string    `bson:"agent_id"`      // ID of the AIAgent performing the action, required
	Action    string    `bson:"action"`        // Type of action performed (e.g., "task_started", "tool_used"), required
	Details   string    `bson:"details"`       // Additional context about the action, required
	Timestamp time.Time `bson:"timestamp"`     // Time the action occurred, required
}

// Notes:
// - Action examples are suggestive; a controlled vocabulary can be enforced in the service layer.
// - Edge cases: Details may be lengthy; truncation or size limits can be applied in the AuditLogRepository.
// - Assumption: AgentID references a valid AIAgent, validated in the service layer.
// - Limitation: No explicit expiration; logs persist unless a cleanup mechanism is added later.
