package entities

import "time"

// Conversation represents a chat-based interaction related to a task in the workflow automation platform.
// It is stored in MongoDB as a document in the 'conversations' collection and contains a list of messages
// exchanged between humans and agents for oversight or input.
//
// Key features:
// - Task linkage: Ties the conversation to a specific Task via TaskID.
// - Message history: Embeds a list of Message objects for full context.
//
// Relationships:
// - One-to-one with Task via TaskID.
type Conversation struct {
	ID        string    `bson:"_id,omitempty"` // Unique identifier, auto-generated by MongoDB if omitted
	TaskID    string    `bson:"task_id"`       // ID of the associated Task, required
	Messages  []Message `bson:"messages"`      // List of messages in the conversation, required
	CreatedAt time.Time `bson:"created_at"`    // Timestamp of creation, set on insert
	UpdatedAt time.Time `bson:"updated_at"`    // Timestamp of last update, updated on modification
}

// Notes:
// - Messages is required per the spec, but an empty slice is valid at creation; validation occurs in the service layer.
// - Edge cases: Conversations with no Messages are possible initially but should populate during interaction.
// - Assumption: TaskID references a valid Task, validated in the ChatService.
// - Limitation: No explicit archival mechanism; old conversations remain unless explicitly deleted.
