package entities

import "time"

// Tool represents a tool available to AI agents in the workflow automation platform.
// It is stored in MongoDB as a document in the 'tools' collection and defines
// a reusable action that agents can execute (e.g., search, file operations).
//
// Key features:
// - Categorization: Groups tools by type (e.g., "search", "file", "bash") for organization.
// - Lifecycle tracking: Includes timestamps for creation and updates.
//
// Relationships:
// - Many-to-many with AIAgent via the Tools field in AIAgent (list of Tool IDs).
type Tool struct {
	ID        string    `bson:"_id,omitempty"` // Unique identifier, auto-generated by MongoDB if omitted
	Name      string    `bson:"name"`          // Human-readable name of the tool, required
	Category  string    `bson:"category"`      // Type of tool (e.g., "search", "file", "bash"), required
	CreatedAt time.Time `bson:"created_at"`    // Timestamp of creation, set on insert
	UpdatedAt time.Time `bson:"updated_at"`    // Timestamp of last update, updated on modification
}

// Notes:
// - ID is a string to align with MongoDB's ObjectID converted to hex string.
// - Category enforces a controlled vocabulary, validated in the service layer.
// - Edge cases: Duplicate Names are allowed but should be unique within a Category for clarity.
// - Assumption: Timestamps are in UTC for consistency across the application.
