name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

permissions:
  contents: write  # Grants permission to create releases and upload assets

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Build binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o aiagent-linux-x86_64 ./cmd/aiagent
          GOOS=linux GOARCH=arm64 go build -o aiagent-linux-arm64 ./cmd/aiagent
          GOOS=windows GOARCH=amd64 go build -o aiagent-windows-x86_64.exe ./cmd/aiagent
          GOOS=darwin GOARCH=amd64 go build -o aiagent-macos-x86_64 ./cmd/aiagent
          GOOS=darwin GOARCH=arm64 go build -o aiagent-macos-arm64 ./cmd/aiagent

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            aiagent-linux-x86_64
            aiagent-linux-arm64
            aiagent-windows-x86_64.exe
            aiagent-macos-x86_64
            aiagent-macos-arm64
